apiVersion: v1
kind: Service
metadata:
  name: api-server-clusterip
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 18080
    - name: "metrics-port"
      protocol: "TCP"
      port: 2112
      targetPort: 2112
  selector:
    app: api-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: api-server
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - image: <% API_SERVER_IMAGE_NAME %>
          name: api-server
          env:
            - name: PORT
              value: "18080"
            - name: MYSQL_HOST
              value: <% MYSQL_NAMESPACE %>
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASS
              value: "root"
            - name: MYSQL_DATABASE
              value: "first"
          ports:
            - containerPort: 18080
