version: "3.4"
services:
  nginx:
    ports:
      - 3200:80
  front:
    build:
      args:
        WS_BASE_URL: wss://stg.quiz.anyfrog.net/ws/
        API_BASE_URL: https://stg.quiz.anyfrog.net/api/
