version: "3.7"

# 開発用
# Mutagenを利用することでファイルIOを高速化します
#
# Quick Usage
# 1. mutagen v0.12.0-bate1 以上をインストールする(2020/08現在)
#     - for Mac: brew install mutagen-io/mutagen/mutagen-beta
#     - for Win: https://github.com/mutagen-io/mutagen/releases/tag/v0.12.0-beta1
# 2. リポジトリの直下で下のコマンドを実行する
#     - mutagen compose -f docker-compose/mutagen-compose.yaml up

volumes:
  front:
    driver: local

services:
  api-server:
    build: ../app/apiServer/target/docker/stage
    networks:
    - default

  front:
    build:
      dockerfile: ../docker-compose/node/dev.Dockerfile
      context: ../front/
      args:
        WS_BASE_URL: ws://localhost:3200/ws/
        API_BASE_URL: http://localhost:3200/api/
    volumes:
    - front:/usr/src/app
    networks:
    - default
    stdin_open: true

  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/root/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
    - default
    depends_on:
    - front
    - api-server
    ports:
    - 3200:80

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    front:
      alpha: "../front"
      beta: "volume://front"
      mode: "two-way-resolved"
